---
apiVersion: runfc.br/v1alpha
kind: KonfigSet
metadata:
  name: linux-server
  namespace: default
spec:
  selectors:
    - konfignodes.runfc.br/name=nebuchadnezzar
  configurations:
    sysctls:
      - name: fs.nr_open
        value: "1048576"
    files:
      - source: k8s://configmap/motd
        key: content  # which configmap key to get information from
        destination: /tmp/motd
        mode: 0644
        ensure: exists
        namespace: configs
      - source: k8s://configmap/hosts
        destination: /tmp/hosts
        mode: 0600
        ensure: exists
        key: hosts
      - source: static://
        destination: /tmp/afile
        mode: 0644
        content: |
          This is a file managed by konfig (don't touch this)

          Well, you can touch it.  But, as long as live, I would
          always fix it back.

---
apiVersion: runfc.br/v1alpha
kind: KonfigSet
metadata:
  name: basic-box
  namespace: default
spec:
  selectors:
    - konfignodes.runfc.br/name=nebuchadnezzar
  configurations:
    files:
      - source: k8s://configmap/motd
        key: content  # which configmap key to get information from
        destination: /tmp/basic
        mode: 0644
        ensure: exists
        namespace: configs

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: motd
  namespace: configs
data:
  content: |
    Welcome to the Konfig Managed Machine

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hosts
  namespace: default
data:
  hosts: |
    127.0.0.1 localhost lo
    ::1       localhost lo
